# Build with latest nodejs available on Travis
language: node_js

# Lock compatible node versions
node_js:
  - "node"
  - "9"
  - "8"

# Build on Ubuntu Trust 14.04
dist: trusty

# "sudo: required" forces build in a complete virtual environment rather than containerized
sudo: required

# Build and Test
script:
  - yarn test
  - yarn build

# Publish coverage results to coveralls.io
after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "coveralls < coverage/lcov.info"

# Deploy to GitHub Releases (api key is encrypted)
# Deploy only master built on latest stable version of node
deploy:
  provider: script
  # skip_cleanup is required to prevent purging files needed for the release on deploy
  skip_cleanup: true
  # run semantic-version script to appropriately increment version
  script:
      - npx travis-deploy-once "npx semantic-release --debug"
